spring.security.oauth2.client:
        registration:
          kakao:
            client-id: a5487753d1cfdb999c88c7fb96f0288b
            redirect-uri: http://43.202.25.203:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            client-secret: NaeJanGo
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client_name: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: 'TeamNaeJanGo'
  access-token:
    header: 'Authorization'
    prefix: 'Bearer '
    expiration-length: 30 # min
  refresh-token:
    header: 'RefreshToken'
    prefix: 'RefreshToken '
    expiration-length: 14 # day
  iss: 'TeamNaeJanGo'
